#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5.QtGui import QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
from page2 import  Ui_page2
from page3 import  Ui_page3
class Ui_page1(object):
    
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_page2()
        self.ui.setupUi(self.window)
        page1.hide()
        self.window.show()
        
    def setupUi(self, page1):
        page1.setObjectName("page1")
        page1.resize(801, 681)
        page1.setStyleSheet("QWidget#page1_centralwidget{\n"
"background-image:url(:/background/WhatsApp Image 2021-11-12 at 12.14.33 PM.jpeg);}")
        self.page1_centralwidget = QtWidgets.QWidget(page1)
        self.page1_centralwidget.setObjectName("page1_centralwidget")
        self.welcome = QtWidgets.QLabel(self.page1_centralwidget)
        self.welcome.setGeometry(QtCore.QRect(140, 70, 521, 151))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue")
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        self.welcome.setFont(font)
        self.welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome.setObjectName("welcome")
        self.label = QtWidgets.QLabel(self.page1_centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 199, 801, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.page1_centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 250, 801, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.page1_centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 300, 801, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.start_Button = QtWidgets.QPushButton(self.page1_centralwidget)
        self.start_Button.setGeometry(QtCore.QRect(250, 410, 281, 91))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.start_Button.setFont(font)
        self.start_Button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.start_Button.setObjectName("start_Button")
        
        self.start_Button.clicked.connect(self.openWindow)
        
        page1.setCentralWidget(self.page1_centralwidget)
        self.statusbar = QtWidgets.QStatusBar(page1)
        self.statusbar.setObjectName("statusbar")
        page1.setStatusBar(self.statusbar)

        self.retranslateUi(page1)
        QtCore.QMetaObject.connectSlotsByName(page1)

    def retranslateUi(self, page1):
        _translate = QtCore.QCoreApplication.translate
        page1.setWindowTitle(_translate("page1", "Page 1"))
        self.welcome.setText(_translate("page1", "Welcome"))
        self.label.setText(_translate("page1", "This application allows user to view"))
        self.label_3.setText(_translate("page1", "Cardiotocography result and"))
        self.label_2.setText(_translate("page1", "show the fetal health status"))
        self.start_Button.setText(_translate("page1", "Start"))

#from resource import background_rc

class Ui_page2(object):
    
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_page3()
        self.ui.setupUi(self.window)
        page2.hide()
        self.window.show()
    
    def setupUi(self, page2):
        page2.setObjectName("page2")
        page2.resize(800, 700)
        page2.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(page2)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, 360, 751, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.corrButton = QtWidgets.QRadioButton(self.frame)
        self.corrButton.setGeometry(QtCore.QRect(90, 20, 531, 31))
        self.corrButton.setObjectName("corrButton")
        self.uterineButton = QtWidgets.QRadioButton(self.frame)
        self.uterineButton.setGeometry(QtCore.QRect(90, 90, 621, 31))
        self.uterineButton.setObjectName("uterineButton")
        self.movementButton = QtWidgets.QRadioButton(self.frame)
        self.movementButton.setGeometry(QtCore.QRect(90, 140, 591, 31))
        self.movementButton.setObjectName("movementButton")
        self.aspectButton = QtWidgets.QRadioButton(self.frame)
        self.aspectButton.setGeometry(QtCore.QRect(90, 190, 631, 23))
        self.aspectButton.setObjectName("aspectButton")
        self.cor_label2 = QtWidgets.QLabel(self.frame)
        self.cor_label2.setGeometry(QtCore.QRect(120, 50, 361, 19))
        self.cor_label2.setObjectName("cor_label2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(129, 30, 530, 70))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.month_label = QtWidgets.QLabel(self.centralwidget)
        self.month_label.setGeometry(QtCore.QRect(230, 210, 130, 60))
        self.month_label.setObjectName("month_label")
        self.year_label = QtWidgets.QLabel(self.centralwidget)
        self.year_label.setGeometry(QtCore.QRect(230, 140, 130, 60))
        self.year_label.setObjectName("year_label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 610, 112, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.pushButton_2.clicked.connect(self.openWindow)
        
        self.yearBox = QtWidgets.QComboBox(self.centralwidget)
        self.yearBox.setGeometry(QtCore.QRect(410, 160, 151, 25))
        self.yearBox.setObjectName("yearBox")
        self.yearBox.addItem("")
        self.yearBox.addItem("")
        self.yearBox.addItem("")
        self.yearBox.addItem("")
        self.yearBox.addItem("")
        self.monthBox = QtWidgets.QComboBox(self.centralwidget)
        self.monthBox.setGeometry(QtCore.QRect(410, 230, 151, 25))
        self.monthBox.setObjectName("monthBox")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
        self.monthBox.addItem("")
       # self.condition_label = QtWidgets.QLabel(self.centralwidget)
       # self.condition_label.setGeometry(QtCore.QRect(229, 280, 181, 60))
       # self.condition_label.setObjectName("condition_label")
       # self.conditionBox = QtWidgets.QComboBox(self.centralwidget)
       # self.conditionBox.setGeometry(QtCore.QRect(410, 300, 151, 25))
       # self.conditionBox.setObjectName("conditionBox")
        #self.conditionBox.addItem("")
       # self.conditionBox.addItem("")
       # self.conditionBox.addItem("")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 681))
        self.widget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.995763, y2:0.96, stop:0 rgba(53, 233, 242, 255), stop:1 rgba(255, 0, 127, 255));")
        self.widget.setObjectName("widget")
        self.widget.raise_()
        self.frame.raise_()
        self.label.raise_()
        self.month_label.raise_()
        self.year_label.raise_()
        self.pushButton_2.raise_()
        self.yearBox.raise_()
        self.monthBox.raise_()
      #  self.condition_label.raise_()
      #  self.conditionBox.raise_()
        page2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(page2)
        self.statusbar.setObjectName("statusbar")
        page2.setStatusBar(self.statusbar)

        self.retranslateUi(page2)
        QtCore.QMetaObject.connectSlotsByName(page2)

    def retranslateUi(self, page2):
        _translate = QtCore.QCoreApplication.translate
        page2.setWindowTitle(_translate("page2", "Page 2"))
        self.corrButton.setText(_translate("page2", "Correlation between the fetal health and the fetal heart rate baseline,"))
        self.uterineButton.setText(_translate("page2", "Effect of uterine contraction to fetal heart rate"))
        self.movementButton.setText(_translate("page2", "Fetal movement and uterine contraction effecting the fetal health"))
        self.aspectButton.setText(_translate("page2", "Aspects that will influnce fetal health"))
        self.cor_label2.setText(_translate("page2", "fetal movement and acceleration per second"))
        self.label.setText(_translate("page2", "View fetal health data"))
        self.month_label.setText(_translate("page2", "MONTH"))
        self.year_label.setText(_translate("page2", "YEAR"))
        self.pushButton_2.setText(_translate("page2", "Analyze"))
        
        
        self.yearBox.setItemText(0, _translate("page2", "1980"))
        self.yearBox.setItemText(1, _translate("page2", "1995"))
        self.yearBox.setItemText(2, _translate("page2", "1996"))
        self.yearBox.setItemText(3, _translate("page2", "1997"))
        self.yearBox.setItemText(4, _translate("page2", "1998"))
        self.monthBox.setItemText(0, _translate("page2", "January"))
        self.monthBox.setItemText(1, _translate("page2", "Ferbuary"))
        self.monthBox.setItemText(2, _translate("page2", "March"))
        self.monthBox.setItemText(3, _translate("page2", "April"))
        self.monthBox.setItemText(4, _translate("page2", "May"))
        self.monthBox.setItemText(5, _translate("page2", "Jun"))
        self.monthBox.setItemText(6, _translate("page2", "July"))
        self.monthBox.setItemText(7, _translate("page2", "August"))
        self.monthBox.setItemText(8, _translate("page2", "September"))
        self.monthBox.setItemText(9, _translate("page2", "October"))
        self.monthBox.setItemText(10, _translate("page2", "November"))
        self.monthBox.setItemText(11, _translate("page2", "December"))
       # self.condition_label.setText(_translate("page2", "FETAL CONDITION"))
       # self.conditionBox.setItemText(0, _translate("page2", "Normal"))
       # self.conditionBox.setItemText(1, _translate("page2", "Suspect"))
       # self.conditionBox.setItemText(2, _translate("page2", "Pathologic"))

   #  if self.movementButton.isChecked()=="True"
   #     self.pixmap=QPixmap('a.png')
             

   # def butttonClick(self):
class Ui_page3(object):
    def setupUi(self, page3):
        page3.setObjectName("page3")
        page3.resize(800, 700)
        self.centralwidget = QtWidgets.QWidget(page3)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 30, 500, 100))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.displaygraph = QtWidgets.QWidget(self.centralwidget)
        self.displaygraph.setGeometry(QtCore.QRect(40, 160, 721, 501))
        self.displaygraph.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.displaygraph.setObjectName("displaygraph")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 681))
        self.widget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0.995763, y2:0.96, stop:0 rgba(53, 233, 242, 255), stop:1 rgba(255, 0, 127, 255));")
        self.widget.setObjectName("widget")
        self.widget.raise_()
        self.label.raise_()
        self.displaygraph.raise_()
        page3.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(page3)
        self.statusbar.setObjectName("statusbar")
        page3.setStatusBar(self.statusbar)

        self.retranslateUi(page3)
        QtCore.QMetaObject.connectSlotsByName(page3)
        

    def retranslateUi(self, page3):
        _translate = QtCore.QCoreApplication.translate
        page3.setWindowTitle(_translate("page3", "Page 3"))
        self.label.setText(_translate("page3", "GRAPH ANALYSIS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page1 = QtWidgets.QMainWindow()
    page2 = QtWidgets.QMainWindow()
    ui = Ui_page1()
    ui.setupUi(page1)
    page1.show()
    sys.exit(app.exec_())

