# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scoop2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(625, 382)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 0, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(10, 210, 61, 16))
        self.label_10.setObjectName("label_10")
        self.calculateButton = QtWidgets.QPushButton(Dialog)
        self.calculateButton.setGeometry(QtCore.QRect(10, 260, 93, 28))
        self.calculateButton.setObjectName("calculateButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 260, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.total_textBox = QtWidgets.QTextEdit(Dialog)
        self.total_textBox.setGeometry(QtCore.QRect(110, 200, 104, 31))
        self.total_textBox.setObjectName("total_textBox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(420, 60, 25, 64))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.boba = QtWidgets.QCheckBox(self.widget)
        self.boba.setText("")
        self.boba.setObjectName("boba")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.boba)
        self.cchip = QtWidgets.QCheckBox(self.widget)
        self.cchip.setText("")
        self.cchip.setObjectName("cchip")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.cchip)
        self.sprink = QtWidgets.QCheckBox(self.widget)
        self.sprink.setText("")
        self.sprink.setObjectName("sprink")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sprink)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(110, 60, 18, 110))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vanila = QtWidgets.QRadioButton(self.widget1)
        self.vanila.setText("")
        self.vanila.setObjectName("vanila")
        self.verticalLayout.addWidget(self.vanila)
        self.choc = QtWidgets.QRadioButton(self.widget1)
        self.choc.setText("")
        self.choc.setObjectName("choc")
        self.verticalLayout.addWidget(self.choc)
        self.Straw = QtWidgets.QRadioButton(self.widget1)
        self.Straw.setText("")
        self.Straw.setObjectName("Straw")
        self.verticalLayout.addWidget(self.Straw)
        self.corn = QtWidgets.QRadioButton(self.widget1)
        self.corn.setText("")
        self.corn.setObjectName("corn")
        self.verticalLayout.addWidget(self.corn)
        self.durian = QtWidgets.QRadioButton(self.widget1)
        self.durian.setText("")
        self.durian.setObjectName("durian")
        self.verticalLayout.addWidget(self.durian)
        self.widget2 = QtWidgets.QWidget(Dialog)
        self.widget2.setGeometry(QtCore.QRect(10, 34, 66, 133))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_2 = QtWidgets.QLabel(self.widget2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_20 = QtWidgets.QLabel(self.widget2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.label_19 = QtWidgets.QLabel(self.widget2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.widget3 = QtWidgets.QWidget(Dialog)
        self.widget3.setGeometry(QtCore.QRect(305, 34, 89, 87))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.widget3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.widget3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.widget3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.widget3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.widget4 = QtWidgets.QWidget(Dialog)
        self.widget4.setGeometry(QtCore.QRect(525, 47, 30, 87))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.widget4)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_17 = QtWidgets.QLabel(self.widget4)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget4)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_16 = QtWidgets.QLabel(self.widget4)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.widget5 = QtWidgets.QWidget(Dialog)
        self.widget5.setGeometry(QtCore.QRect(200, 40, 30, 133))
        self.widget5.setObjectName("widget5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.widget5)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.label_13 = QtWidgets.QLabel(self.widget5)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_5.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.widget5)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.widget5)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_22 = QtWidgets.QLabel(self.widget5)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.label_21 = QtWidgets.QLabel(self.widget5)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "SCOOP"))
        self.label_10.setText(_translate("Dialog", "Total"))
        self.calculateButton.setText(_translate("Dialog", "Calculate"))
        self.pushButton_2.setText(_translate("Dialog", "Reset"))
        self.label_5.setText(_translate("Dialog", "Flavour"))
        self.label_2.setText(_translate("Dialog", "Vanilla"))
        self.label_3.setText(_translate("Dialog", "Chocolate"))
        self.label_4.setText(_translate("Dialog", "Strawberry"))
        self.label_20.setText(_translate("Dialog", "Corn"))
        self.label_19.setText(_translate("Dialog", "Durian"))
        self.label_9.setText(_translate("Dialog", "Topping"))
        self.label_8.setText(_translate("Dialog", "Boba"))
        self.label_7.setText(_translate("Dialog", "chcocolate chip"))
        self.label_6.setText(_translate("Dialog", "sprinkle"))
        self.label_12.setText(_translate("Dialog", "price"))
        self.label_17.setText(_translate("Dialog", "0.8"))
        self.label_18.setText(_translate("Dialog", "0.3"))
        self.label_16.setText(_translate("Dialog", "0.5"))
        self.label_11.setText(_translate("Dialog", "price"))
        self.label_13.setText(_translate("Dialog", "2.02"))
        self.label_15.setText(_translate("Dialog", "1.40"))
        self.label_14.setText(_translate("Dialog", "1.66"))
        self.label_22.setText(_translate("Dialog", "3.00"))
        self.label_21.setText(_translate("Dialog", "5.00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

